/**
 * The configuration refuses to guess, everywhere a guess would cost money.
 *
 * Commit f443fd8 in this repository deleted a `?? "galileo"` from the inference
 * client: a caller who omitted the field traded on 16661 while their inference
 * ran on 16602, and nothing threw, because both halves succeed on their own and
 * the two provider catalogues are disjoint. `modeForChainId` had already taken
 * the same position for chain ids and says so in its own message — the guess it
 * replaced was localhost, "which looks like an empty protocol rather than a
 * misconfiguration".
 *
 * A trader is the worst place to keep guessing: a keeper pointed the wrong way
 * only spends gas, while this one holds addresses that name different contracts
 * on a different chain. So there is no default chain here, the RPC is derived
 * from the chain id rather than defaulted beside it, and the endpoint is then
 * asked to confirm which chain it actually is.
 */
import {afterAll, beforeAll, describe, expect, it} from "vitest";
import {existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {fileURLToPath} from "node:url";
import {networkForChainId} from "@0g-brier/protocol";
import {assertChainMatches, dryBudgetTokens, envWithArgv, readConfig, type Env} from "../src/config.js";
import {loadSrc} from "./source.js";
import {closedPortUrl, startStubRpc, type StubRpc} from "./stub-rpc.js";

/** Synthetic, and never a real key: 32 bytes of `0xab`, generated by repetition. */
const FAKE_KEY = `0x${"ab".repeat(32)}`;

const MAINNET = 16661;
const GALILEO = 16602;

/** A manifest of this project's own making, so these tests hold in a copied-out one too. */
const MANIFEST_FACTORY = "0xAbCdEf0123456789AbCdEf0123456789AbCdEf01";
const MANIFEST_SHARES = "0x0123456789AbCdEf0123456789AbCdEf01234567";

let manifestDir: string;
let emptyDir: string;

beforeAll(() => {
  manifestDir = mkdtempSync(join(tmpdir(), "brier-example-agent-manifest-"));
  emptyDir = mkdtempSync(join(tmpdir(), "brier-example-agent-empty-"));
  writeFileSync(
    join(manifestDir, `${GALILEO}.json`),
    JSON.stringify({
      chainId: GALILEO,
      deploymentBlock: 1,
      deployedAt: 1,
      contracts: {MarketFactory: MANIFEST_FACTORY, OutcomeShares: MANIFEST_SHARES},
    }),
  );
});

afterAll(() => {
  rmSync(manifestDir, {recursive: true, force: true});
  rmSync(emptyDir, {recursive: true, force: true});
});

/** A dry run on Galileo, reading the fabricated manifest. Nothing here signs. */
function dryEnv(over: Env = {}): Env {
  return {
    CHAIN_ID: String(GALILEO),
    DRY_RUN: "1",
    DRY_BUDGET: "1",
    DEPLOYMENTS_DIR: manifestDir,
    ...over,
  };
}

describe("there is no default chain", () => {
  it("refuses an unset CHAIN_ID and says why there is no default", () => {
    let message = "";
    try {
      readConfig({DEPLOYMENTS_DIR: manifestDir});
    } catch (error: unknown) {
      message = error instanceof Error ? error.message : String(error);
    }
    expect(message).toMatch(/CHAIN_ID is required/);
    // Naming both chains is the point: the failure has to say what it would
    // have had to guess between.
    expect(message).toContain("16661");
    expect(message).toContain("16602");
  });

  it("refuses a CHAIN_ID that is not an integer", () => {
    expect(() => readConfig(dryEnv({CHAIN_ID: "galileo"}))).toThrow(/not an integer/);
    expect(() => readConfig(dryEnv({CHAIN_ID: "16602.5"}))).toThrow(/not an integer/);
  });

  it("refuses a chain id it does not know, rather than falling back to localhost", () => {
    // 1 is Ethereum. An agent that quietly treated it as anvil would report an
    // empty protocol instead of a misconfiguration — the exact failure
    // `modeForChainId` was written to end.
    expect(() => readConfig(dryEnv({CHAIN_ID: "1"}))).toThrow(/not a known 0G network/);
    expect(() => readConfig(dryEnv({CHAIN_ID: "1"}))).toThrow(/Refusing to guess/);
  });

  it("no source file defaults a network, a chain id or an endpoint", () => {
    // The same scan `packages/agent-kit/test/network-boundary.test.ts` runs over
    // the SDK, over this project's four files.
    const files = loadSrc();
    expect(files.map((f) => f.name)).toEqual(["agent.ts", "config.ts", "redeem.ts", "strategy.ts"]);
    for (const file of files) {
      for (const forbidden of [
        /network\s*(\?\?|\|\|)\s*["'`]/,
        /chainId\s*(\?\?|\|\|)\s*\d/,
        /CHAIN_ID\s*(\?\?|\|\|)/,
        /["'`]https?:\/\//,
      ]) {
        const hit = file.code.match(forbidden);
        expect(hit?.[0], `src/${file.name} defaults something it must not: ${hit?.[0]}`).toBeUndefined();
      }
    }
  });
});

describe("the RPC follows the chain id rather than sitting beside it", () => {
  it("derives each endpoint from the chain id it was given", () => {
    for (const chainId of [MAINNET, GALILEO, 31337]) {
      const config = readConfig(dryEnv({CHAIN_ID: String(chainId), FACTORY: MANIFEST_FACTORY, OUTCOME_SHARES: MANIFEST_SHARES}));
      expect(config.chainId).toBe(chainId);
      expect(config.rpcUrl).toBe(networkForChainId(chainId, {}).rpcUrl);
    }
  });

  it("puts mainnet on the mainnet endpoint and Galileo on the testnet one", () => {
    const mainnet = readConfig(dryEnv({CHAIN_ID: String(MAINNET), FACTORY: MANIFEST_FACTORY, OUTCOME_SHARES: MANIFEST_SHARES}));
    const galileo = readConfig(dryEnv());
    expect(mainnet.network).toBe("mainnet");
    expect(mainnet.rpcUrl).toBe("https://evmrpc.0g.ai");
    expect(galileo.network).toBe("galileo");
    expect(galileo.rpcUrl).toBe("https://evmrpc-testnet.0g.ai");
    // And the storage indexers differ too, because the two storage networks
    // share no data and a testnet indexer cannot answer for a mainnet market.
    expect(mainnet.indexerUrl).not.toBe(galileo.indexerUrl);
  });

  it("keeps an RPC_URL that was given, because that is the one that can be wrong", () => {
    const config = readConfig(dryEnv({RPC_URL: "http://127.0.0.1:8545"}));
    expect(config.rpcUrl).toBe("http://127.0.0.1:8545");
    expect(config.chainId).toBe(GALILEO);
  });
});

describe("the endpoint is asked to confirm which chain it is", () => {
  let galileoStub: StubRpc;

  beforeAll(async () => {
    galileoStub = await startStubRpc(GALILEO);
  });
  afterAll(async () => {
    await galileoStub.close();
  });

  it("accepts an endpoint that reports the configured chain", async () => {
    const config = readConfig(dryEnv({RPC_URL: galileoStub.url}));
    await expect(assertChainMatches(config)).resolves.toBeUndefined();
  });

  it("refuses an endpoint that reports a different chain, naming both", async () => {
    // A URL can point anywhere; Galileo has been reset onto a new chain id
    // twice. This is the check that catches an endpoint repointed after the
    // configuration was written down.
    const config = readConfig(
      dryEnv({
        CHAIN_ID: String(MAINNET),
        RPC_URL: galileoStub.url,
        FACTORY: MANIFEST_FACTORY,
        OUTCOME_SHARES: MANIFEST_SHARES,
      }),
    );
    await expect(assertChainMatches(config)).rejects.toThrow(/CHAIN_ID is 16661 but .* reports 16602/);
  });

  it("refuses an endpoint that never identified itself", async () => {
    const config = readConfig(dryEnv({RPC_URL: await closedPortUrl()}));
    await expect(assertChainMatches(config)).rejects.toThrow(/could not read a chain id/);
  }, 20_000);
});

describe("the key is required to trade, and is not part of the configuration", () => {
  it("refuses to run without one and points at the dry run instead", () => {
    let message = "";
    try {
      readConfig({CHAIN_ID: String(GALILEO), DEPLOYMENTS_DIR: manifestDir});
    } catch (error: unknown) {
      message = error instanceof Error ? error.message : String(error);
    }
    expect(message).toMatch(/AGENT_KEY is required/);
    expect(message).toContain("--dry");
  });

  it("never quotes the value it rejected", () => {
    // A message that echoed the offending value to be helpful would put a key —
    // possibly a real one, mistyped by a single character — into a terminal, a
    // CI log and a transcript.
    const mistyped = "0xnot-a-key-but-it-would-still-be-a-secret";
    let message = "";
    try {
      readConfig({CHAIN_ID: String(GALILEO), DEPLOYMENTS_DIR: manifestDir, AGENT_KEY: mistyped});
    } catch (error: unknown) {
      message = error instanceof Error ? error.message : String(error);
    }
    expect(message).toMatch(/not a private key/);
    expect(message).not.toContain(mistyped);
    expect(message).not.toContain("not-a-key");
  });

  it("accepts a key with or without its 0x, and keeps neither", () => {
    const withPrefix = readConfig({CHAIN_ID: String(GALILEO), DEPLOYMENTS_DIR: manifestDir, AGENT_KEY: FAKE_KEY});
    const without = readConfig({
      CHAIN_ID: String(GALILEO),
      DEPLOYMENTS_DIR: manifestDir,
      AGENT_KEY: FAKE_KEY.slice(2),
    });
    for (const config of [withPrefix, without]) {
      expect(config.dryRun).toBe(false);
      // A config object is the thing people print when a run misbehaves.
      expect(Object.keys(config).filter((k) => /key|secret|private|mnemonic/i.test(k))).toEqual([]);
      const printed = JSON.stringify(config, (_k, v: unknown) => (typeof v === "bigint" ? v.toString() : v));
      expect(printed).not.toContain(FAKE_KEY.slice(2));
    }
  });
});

describe("a dry run states its budget rather than measuring one", () => {
  it("requires DRY_BUDGET and explains why zero is not a substitute", () => {
    let message = "";
    try {
      readConfig({CHAIN_ID: String(GALILEO), DEPLOYMENTS_DIR: manifestDir, DRY_RUN: "1"});
    } catch (error: unknown) {
      message = error instanceof Error ? error.message : String(error);
    }
    expect(message).toMatch(/DRY_BUDGET is required/);
    expect(message).toContain("no balance to size against");
  });

  it("refuses a budget that is not a plain decimal amount", () => {
    expect(() => readConfig(dryEnv({DRY_BUDGET: "1e18"}))).toThrow(/plain decimal/);
    expect(() => readConfig(dryEnv({DRY_BUDGET: "one"}))).toThrow(/plain decimal/);
  });

  it("parses the budget in the MARKET's decimals, which are not always 18", () => {
    // The mock USDC on Galileo has 6. A budget parsed at 18 there would be a
    // million times the intended order, which is why the string is carried
    // until a market is in hand.
    const config = readConfig(dryEnv({DRY_BUDGET: "1.5"}));
    expect(dryBudgetTokens(config, 6)).toBe(1_500_000n);
    expect(dryBudgetTokens(config, 18)).toBe(1_500_000_000_000_000_000n);
  });

  it("refuses to invent a budget outside a dry run", () => {
    const live = readConfig({CHAIN_ID: String(GALILEO), DEPLOYMENTS_DIR: manifestDir, AGENT_KEY: FAKE_KEY});
    expect(live.dryBudget).toBeNull();
    expect(() => dryBudgetTokens(live, 18)).toThrow(/outside a dry run/);
  });
});

describe("addresses come from a manifest, or from the environment, never from both", () => {
  it("reads the manifest when nothing overrides it", () => {
    const config = readConfig(dryEnv());
    expect(config.addressSource).toBe("manifest");
    expect(config.factory).toBe(MANIFEST_FACTORY);
    expect(config.outcomeShares).toBe(MANIFEST_SHARES);
  });

  it("refuses half an override", () => {
    expect(() => readConfig(dryEnv({FACTORY: MANIFEST_FACTORY}))).toThrow(/must be set together/);
    expect(() => readConfig(dryEnv({OUTCOME_SHARES: MANIFEST_SHARES}))).toThrow(/must be set together/);
  });

  it("accepts an override that agrees with the manifest, whatever its casing", () => {
    // `deployments/16661.json` is written all lowercase and `16602.json` is
    // checksummed, so a case-sensitive comparison would reject one of this
    // repository's own manifests depending on which chain you pointed at.
    const config = readConfig(
      dryEnv({FACTORY: MANIFEST_FACTORY.toLowerCase(), OUTCOME_SHARES: MANIFEST_SHARES.toUpperCase().replace("0X", "0x")}),
    );
    expect(config.addressSource).toBe("environment");
  });

  it("refuses an override that disagrees with the manifest, rather than choosing", () => {
    const other = "0x1111111111111111111111111111111111111111";
    expect(() => readConfig(dryEnv({FACTORY: other, OUTCOME_SHARES: MANIFEST_SHARES}))).toThrow(
      /disagrees with deployments/,
    );
  });

  it("refuses an address that is not one", () => {
    expect(() => readConfig(dryEnv({FACTORY: "0x1234", OUTCOME_SHARES: MANIFEST_SHARES}))).toThrow(/is not an address/);
    expect(() => readConfig(dryEnv({MARKET: "not-an-address"}))).toThrow(/is not an address/);
  });

  it("works with no manifest at all, which is what a copied-out project has", () => {
    const config = readConfig(
      dryEnv({DEPLOYMENTS_DIR: emptyDir, FACTORY: MANIFEST_FACTORY, OUTCOME_SHARES: MANIFEST_SHARES}),
    );
    expect(config.addressSource).toBe("environment");
  });

  it("refuses to run with neither, and says which two variables would answer", () => {
    let message = "";
    try {
      readConfig(dryEnv({DEPLOYMENTS_DIR: emptyDir}));
    } catch (error: unknown) {
      message = error instanceof Error ? error.message : String(error);
    }
    expect(message).toMatch(/no deployment for chain 16602/);
    expect(message).toContain("FACTORY");
    expect(message).toContain("OUTCOME_SHARES");
  });
});

describe("inside this repository, the manifest is the live deployment", () => {
  const deployments = fileURLToPath(new URL("../../deployments", import.meta.url));
  const mainnetManifest = join(deployments, `${MAINNET}.json`);
  const insideTheRepo = existsSync(mainnetManifest);

  // A copied-out project has no `deployments/` directory and is expected to set
  // FACTORY and OUTCOME_SHARES instead — the case the test above covers
  // unconditionally. This one is about the default path working in place.
  it.skipIf(!insideTheRepo)("finds deployments/16661.json without being told where it is", () => {
    const config = readConfig({CHAIN_ID: String(MAINNET), DRY_RUN: "1", DRY_BUDGET: "1"});
    const manifest = JSON.parse(readFileSync(mainnetManifest, "utf8")) as {
      contracts: Record<string, string>;
    };
    expect(config.addressSource).toBe("manifest");
    // Compared against the file rather than against an address typed in here:
    // the addresses live in the manifest, and a copy of them in a test is a
    // second source of truth waiting to disagree.
    expect(config.factory).toBe(manifest.contracts.MarketFactory);
    expect(config.outcomeShares).toBe(manifest.contracts.OutcomeShares);
  });
});

describe("the risk limits are read, not assumed", () => {
  it("defaults each one to the number src/config.ts cites a source for", () => {
    const config = readConfig(dryEnv());
    expect(config.maxImpactBps).toBe(500n);
    expect(config.minEdgeBps).toBe(0n);
    expect(config.slippageBps).toBe(100n);
    expect(config.bankrollCapBps).toBe(2500n);
  });

  it("takes them from the environment when they are set", () => {
    const config = readConfig(dryEnv({MAX_IMPACT_BPS: "250", MIN_EDGE_BPS: "50", SLIPPAGE_BPS: "10", BANKROLL_CAP_BPS: "1000"}));
    expect([config.maxImpactBps, config.minEdgeBps, config.slippageBps, config.bankrollCapBps]).toEqual([
      250n,
      50n,
      10n,
      1000n,
    ]);
  });

  it("refuses a fraction of a basis point and a limit above 100%", () => {
    expect(() => readConfig(dryEnv({MAX_IMPACT_BPS: "5.5"}))).toThrow(/whole number of basis points/);
    expect(() => readConfig(dryEnv({SLIPPAGE_BPS: "10001"}))).toThrow(/more than 100%/);
  });
});

describe("--dry and DRY_RUN mean the same thing", () => {
  it("folds the flag into the environment", () => {
    const env: Env = {CHAIN_ID: String(GALILEO)};
    expect(envWithArgv(env, ["node", "src/agent.ts", "--dry"]).DRY_RUN).toBe("1");
    // `DRY_RUN=1 tsx …` is shell syntax that does not run on Windows, which is
    // why the flag exists at all.
    expect(env.DRY_RUN, "envWithArgv mutated the environment it was handed").toBeUndefined();
  });

  it("leaves the environment alone without the flag", () => {
    const env: Env = {CHAIN_ID: String(GALILEO)};
    expect(envWithArgv(env, ["node", "src/agent.ts"])).toBe(env);
  });
});
